### ISSUE TITLE
Deselect in multi select environment

### ISSUE THREAD

**Issue by halfsoft** [devlinb/react-native-simple-survey#3]
You cannot deselect elements by clicking again on them, if there is a limit of max 3 elements you can click on the same element 3 times to deselect all prior ones.

**Comment by devlinb** [comment]
I never needed deselect so I didn't implement it!

Obviously for multi-select where the user can choose between 1 and n items, deselect should be implemented. My bad.

**Comment by XW-Yanis** [comment]
@devlinb Hi devlinb, I have no ideas how to write a snapshot test for SurveyScreen and SurveyCompletedScreen, could you give a help?

**Comment by sunnyarain** [comment]
Hi @devlinb how can we achieve preselected answer for a specific question?

**Comment by devlinb** [comment]
@halfsoft @XW-Yanis 

2.0 is a breaking change but it should do everything you need. Lots of new features, have fun!
